workflow:
  name: m4-team terraform Pipeline
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
      when: always
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always

image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest

stages:
  - validate
  - build
  - deploy

validate:
  stage: validate
  script:
    - gitlab-terraform init
    - gitlab-terraform validate

plan:
  stage: build
  script:
    - gitlab-terraform init
    - gitlab-terraform plan
    - gitlab-terraform plan-json
  artifacts:
    name: plan
    paths:
      - plan.cache
    when: on_success
    reports:
      terraform: plan.json

apply:
  stage: deploy
  script:
    - gitlab-terraform apply
  dependencies:
    - plan
  only:
    - main