kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: iamuser-eks-binding
subjects:
- kind: User
  name: iamuser-eksuser
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: iamuser-eks-role
  apiGroup: rbac.authorization.k8s.io